# Generated by Django 3.1.14 on 2023-09-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0006_increase_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_packages', models.CharField(blank=True, max_length=200, null=True)),
                ('tour_place', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'tour_package',
                'verbose_name_plural': 'tour_packages',
            },
        ),
        migrations.CreateModel(
            name='MainPackageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('package_place', models.CharField(blank=True, max_length=100, null=True)),
                ('package_days', models.IntegerField(blank=True, null=True)),
                ('package_price', models.IntegerField()),
                ('packages_include_1', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_2', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_3', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_4', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_5', models.CharField(blank=True, max_length=100, null=True)),
                ('package_short_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
            ],
            options={
                'verbose_name': 'MainPackage',
                'verbose_name_plural': 'MainPackages',
            },
        ),
        migrations.CreateModel(
            name='HomePackages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('package_place', models.CharField(blank=True, max_length=100, null=True)),
                ('package_days', models.IntegerField(blank=True, null=True)),
                ('package_price', models.IntegerField()),
                ('packages_include_1', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_2', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_3', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_4', models.CharField(blank=True, max_length=100, null=True)),
                ('packages_include_5', models.CharField(blank=True, max_length=100, null=True)),
                ('package_short_description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
            ],
            options={
                'verbose_name': 'HomePackage',
                'verbose_name_plural': 'HomePackages',
            },
        ),
    ]
