# Generated by Django 3.1.14 on 2023-09-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepackages',
            name='packages_include_1',
        ),
        migrations.RemoveField(
            model_name='homepackages',
            name='packages_include_2',
        ),
        migrations.RemoveField(
            model_name='homepackages',
            name='packages_include_3',
        ),
        migrations.RemoveField(
            model_name='homepackages',
            name='packages_include_4',
        ),
        migrations.RemoveField(
            model_name='homepackages',
            name='packages_include_5',
        ),
    ]
