# Generated by Django 3.1.14 on 2023-09-18 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0002_auto_20230918_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepackages',
            name='date_created',
        ),
        migrations.AddField(
            model_name='homepackages',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
