# Generated by Django 3.1.14 on 2023-09-18 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0003_auto_20230918_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepackages',
            name='home',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
