# Generated by Django 3.1.14 on 2023-09-18 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0005_auto_20230918_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepackages',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepackages',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='mainpackageview',
            name='date_updated',
            field=models.DateField(auto_now=True, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='mainpackageview',
            name='date_created',
            field=models.DateField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
