# Generated by Django 3.1.14 on 2023-09-18 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0006_auto_20230918_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepackages',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='homepackages',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='mainpackageview',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='mainpackageview',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='tourpackages',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
