# Generated by Django 3.1.14 on 2023-09-18 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0007_auto_20230918_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackages',
            name='data',
        ),
        migrations.AddField(
            model_name='tourpackages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourpackages',
            name='theDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
