# Generated by Django 3.1.14 on 2023-09-18 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0008_auto_20230918_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackages',
            name='theDate',
        ),
        migrations.AddField(
            model_name='homepackages',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpackageview',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
