# Generated by Django 3.1.14 on 2023-09-18 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0013_auto_20230918_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepackages',
            options={'ordering': ['-date_added'], 'verbose_name': 'HomePackage', 'verbose_name_plural': 'HomePackages'},
        ),
    ]
