# Generated by Django 3.1.14 on 2023-09-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0014_auto_20230918_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepackages',
            name='package_short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainpackageview',
            name='package_short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
