# Generated by Django 3.1.14 on 2023-09-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0015_auto_20230919_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
