# Generated by Django 3.1.14 on 2023-09-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0016_bookings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name': 'Bookings', 'verbose_name_plural': 'Booking'},
        ),
        migrations.AddField(
            model_name='bookings',
            name='additional_request',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='age',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='reserveation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='tour_package',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
