# Generated by Django 3.1.14 on 2023-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0017_auto_20230920_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='age',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
