# Generated by Django 3.1.14 on 2023-09-21 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0018_auto_20230920_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackages',
            name='tour_price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
