# Generated by Django 3.1.14 on 2023-10-06 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0020_auto_20231005_2232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='category',
        ),
        migrations.AddField(
            model_name='mainpackageview',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HetmApp.packagecategory'),
        ),
    ]
