# Generated by Django 3.1.14 on 2023-10-20 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0022_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackages',
            name='MainPackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HetmApp.mainpackageview'),
        ),
    ]
