# Generated by Django 3.1.14 on 2023-10-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0023_tourpackages_mainpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackages',
            name='payment_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
