# Generated by Django 3.1.14 on 2023-10-21 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0024_tourpackages_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackages',
            name='MainPackage',
        ),
        migrations.AlterField(
            model_name='tourpackages',
            name='tour_packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HetmApp.mainpackageview'),
        ),
    ]
