# Generated by Django 3.1.14 on 2023-10-21 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HetmApp', '0025_auto_20231021_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackages',
            old_name='tour_packages',
            new_name='tour_package',
        ),
    ]
